version: '3.8'

services:
  general-discord-bot:
    image: ghcr.io/bignellrp/general-discord-bot:main
    container_name: general-discord-bot
    networks:
      - br1
    restart: always
    env_file:
      - /mnt/docker/general-discord-bot/.env
    environment:
      - TZ=UTC  # Set the container's timezone to UTC to avoid daylight saving issues

networks:
  br1:
    external: true
    name: br1